[package]
name = "chip8-cli"
version = "0.14.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
chip8-core = { path = "../chip8-core" }
chip8-drivers = { path = "../chip8-drivers" }
argh = "0.1.6"
tracing-subscriber = "0.2.25"
