[package]
name = "chip8-graphics"
version = "0.1.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]

[dependencies]
chip8-core = { path = "../chip8-core" }
chip8-cpu = { path = "../chip8-cpu" }
sdl2 = "0.31"