version: 2

jobs:
  build:
    docker:
      - image: library/rust:1.34-slim

    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      - run:
          name: Install components
          command: |
            apt-get update -y
            apt-get install libsdl2-dev libsdl2-ttf-dev -y
            rustup component add rustfmt
            rustup toolchain install stable
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt -- --check
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
