[package]
name = "chip8-drivers"
version = "0.14.0"
authors = ["Denis BOURGE <denis.bourge@sharingcloud.com>"]
edition = "2018"

[dependencies]
chip8-core = { path = "../chip8-core" }
cpal = "0.11.0"
macroquad = "0.3.10"
usfx = "0.1.3"
