name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install libsdl2-dev libsdl2-ttf-dev -y
    - name: Build
      run: cargo build --verbose
    - name: Check lints
      run: cargo clippy --verbose --all
    - name: Check format
      run: cargo fmt --verbose --all -- --check
    - name: Run tests
      run: cargo test --verbose --all
