name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo xtask build
    - name: Check lints
      run: cargo xtask lint --error
    - name: Check format
      run: cargo xtask fmt --check
    - name: Run tests
      run: cargo xtask test
